#!/bin/sh
# Build starship.toml = starship.base.toml + colors.toml.
#
# Starship's TOML has no include directive, which is the one place this repo's
# usual "hand-written config imports a generated colors.* file" pattern does not
# work. Concatenation is the whole trick, and the order matters: `palette =` is
# a root key, so it has to precede every table header -- which is why the
# generated [palettes.dots] table goes last.
#
# Called by hypr/scripts/set-wallpaper.sh after matugen. Run it by hand after
# editing starship.base.toml. Starship re-reads its config on every prompt, so
# already-open shells pick the result up with no restart.
set -eu

dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
out="${dir}/starship.toml"

{
	printf '%s\n' '# GENERATED by starship/build.sh -- DO NOT EDIT.'
	printf '%s\n' '# Edit starship.base.toml (prompt) or matugen/templates/colors-starship.toml'
	printf '%s\n' '# (palette), then run ~/dotfiles/starship/build.sh.'
	printf '\n'
	cat "${dir}/starship.base.toml"
	printf '\n'
	cat "${dir}/colors.toml"
} > "${out}.tmp"

mv -f "${out}.tmp" "$out"
