-- GENERATED BY MATUGEN -- DO NOT EDIT. Regenerate: hypr/scripts/set-wallpaper.sh
-- Role choices match colors-hypr.lua / colors-quickshell.qml on purpose: the
-- editor must never drift onto a different accent than the rest of the desktop.
return {
    accent     = "#acc7ff",
    accent_alt = "#cabff8",
    accent_dim = "#004590",
    urgent     = "#ffb4ab",
    surface    = "#262a33",
}
