-- GENERATED BY MATUGEN -- DO NOT EDIT. Regenerate: hypr/scripts/set-wallpaper.sh
-- Override by mutating the returned table in hyprland.lua after the dofile().
-- The accent half follows the wallpaper; bg/fg/border/shadow are the fixed
-- desktop base from matugen/base.json.
return {
    accent     = "acc7ff",
    accent_alt = "ddbce0",
    accent_dim = "294677",
    urgent     = "ffb4ab",
    surface    = "282a2f",

    bg         = '141C21',
    fg         = '93A1A1',
    border     = '3C4449',
    shadow     = '0A0F12',
}
