pragma Singleton

// GENERATED BY MATUGEN -- DO NOT EDIT. Regenerate: hypr/scripts/set-wallpaper.sh
// Role choices are kept identical to colors-waybar.css on purpose: the dashboard
// and the bar must never drift onto different accents.
import QtQuick
import Quickshell

Singleton {
    readonly property color accent: "#acc7ff"
    readonly property color accentAlt: "#cabff8"
    readonly property color accentDim: "#004590"
    readonly property color urgent: "#ffb4ab"
    // Wallpaper-tinted dark surface -- for hovered/selected backgrounds only.
    readonly property color surface: "#262a33"
}
