pragma Singleton

// GENERATED BY MATUGEN -- DO NOT EDIT. Regenerate: hypr/scripts/set-wallpaper.sh
// Role choices are kept identical to colors-waybar.css on purpose: the dashboard
// and the bar must never drift onto different accents.
import QtQuick
import Quickshell

Singleton {
    readonly property color accent: "#e7c400"
    readonly property color accentAlt: "#c4cc84"
    readonly property color accentDim: "#544600"
    readonly property color urgent: "#ffb4ab"
    // Wallpaper-tinted dark surface -- for hovered/selected backgrounds only.
    readonly property color surface: "#2e2a1a"
}
