-- ~/.config/nvim (this dir is symlinked in by link.sh, same as every other
-- top-level dir in the repo). Kept deliberately compact: treesitter, LSP via
-- mason, cmp, telescope, gitsigns -- the everyday set, not a full IDE.

vim.g.mapleader = " "
vim.g.maplocalleader = " "

-- ---------------------------------------------------------------- options --
local o = vim.opt
o.number = true
o.relativenumber = true
o.mouse = "a"
o.clipboard = "unnamedplus" -- shares the system clipboard, so it lines up
-- with cliphist/wl-clipboard (see hypr/hyprland.lua)
o.ignorecase = true
o.smartcase = true
o.termguicolors = true
o.signcolumn = "yes"
o.updatetime = 250
o.expandtab = true
o.shiftwidth = 4
o.tabstop = 4
o.splitright = true
o.splitbelow = true
o.undofile = true
o.scrolloff = 8
o.wrap = true
o.linebreak = true
o.breakindent = true

-- ---------------------------------------------------------------- keymaps --
local map = vim.keymap.set
map("i", "jk", "<Esc>", { desc = "Exit insert mode" })
map("n", "<leader>w", "<cmd>write<cr>", { desc = "Save" })
map("n", "<leader>q", "<cmd>quit<cr>", { desc = "Quit" })
map("n", "<C-h>", "<C-w>h", { desc = "Focus window left" })
map("n", "<C-j>", "<C-w>j", { desc = "Focus window down" })
map("n", "<C-k>", "<C-w>k", { desc = "Focus window up" })
map("n", "<C-l>", "<C-w>l", { desc = "Focus window right" })

-- --------------------------------------------------------------- colours ---
-- GENERATED BY MATUGEN (see matugen/config.toml [templates.nvim]) -- the base
-- background/foreground stay hand-written here, same rule the rest of the
-- rice follows (README "Theming"): only the accent moves with the wallpaper.
-- Does not hot-reload; reopen nvim after SUPER+W to pick up a new accent.
local ok, colors = pcall(dofile, os.getenv("HOME") .. "/dotfiles/nvim/colors.lua")
if not ok then
	colors = { accent = "#acc7ff", accent_alt = "#cabff8", accent_dim = "#004590",
		urgent = "#ffb4ab", surface = "#262a33" }
end
require("theme").apply(colors)

-- ------------------------------------------------------------- bootstrap ---
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.uv.fs_stat(lazypath) then
	vim.fn.system({
		"git", "clone", "--filter=blob:none",
		"https://github.com/folke/lazy.nvim.git",
		"--branch=stable", lazypath,
	})
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup(require("plugins"), {
	lockfile = vim.fn.stdpath("config") .. "/lazy-lock.json",
})
