-- GENERATED BY MATUGEN -- DO NOT EDIT. Regenerate: hypr/scripts/set-wallpaper.sh
-- Override by mutating the returned table in hyprland.lua after the dofile().
return {
    accent     = "ffba4a",
    accent_alt = "dcc578",
    accent_dim = "624000",
    urgent     = "ffb4ab",
}
