-- GENERATED BY MATUGEN -- DO NOT EDIT. Regenerate: hypr/scripts/set-wallpaper.sh
-- Override by mutating the returned table in hyprland.lua after the dofile().
return {
    accent     = "acc7ff",
    accent_alt = "cabff8",
    accent_dim = "004590",
    urgent     = "ffb4ab",
    surface    = "262a33",
}
