-- GENERATED BY MATUGEN -- DO NOT EDIT. Regenerate: hypr/scripts/set-wallpaper.sh
-- Override by mutating the returned table in hyprland.lua after the dofile().
return {
    accent     = "fdbc00",
    accent_alt = "d3c87c",
    accent_dim = "5c4200",
    urgent     = "ffb4ab",
}
