-- LIBVA_DRIVER_NAME lives in ~/.config/environment.d/20-va.conf, not here.
-- Under UWSM only UWSM_FINALIZE_VARNAMES is exported to the systemd user
-- manager, so an hl.env() here would reach Hyprland's own children but never
-- an app launched as a systemd scope -- which is exactly the browser.
--
-- The cursor vars below ARE in UWSM_FINALIZE_VARNAMES, so they propagate.
-- Cursor theme: Bibata if it is installed, Adwaita (always present) otherwise.
-- Checked here rather than hardcoded so the config stays correct on a machine
-- without bibata-cursor-theme. hypr/scripts/gsettings-theme.sh does the same
-- pick for the GTK side, so the two never disagree.
local function cursor_theme()
    for _, name in ipairs({ "Bibata-Modern-Ice", "Bibata-Modern-Classic" }) do
        for _, dir in ipairs({ "/usr/share/icons/", os.getenv("HOME") .. "/.local/share/icons/",
                               os.getenv("HOME") .. "/.icons/" }) do
            local f = io.open(dir .. name .. "/index.theme", "r")
            if f then f:close(); return name end
        end
    end
    return "Adwaita"
end

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("XCURSOR_THEME", cursor_theme())


-- Per-machine overrides: monitor rules, workspace->monitor pinning, keyboard
-- layout, which optional autostarts run. Lives outside the repo entirely
-- (~/.config/hypr is a symlink INTO this repo, so anything written there
-- would sync verbatim to every machine -- same reasoning as 20-va.conf, see
-- install.sh). Generated once by install.sh from hardware/output probes and
-- never overwritten after that; hand-edit freely. Absent (a fresh clone, or a
-- deleted file) just means the generic defaults below stand.
local ok, local_cfg = pcall(dofile, os.getenv("HOME") .. "/.config/dotfiles/local.lua")
local M = (ok and type(local_cfg) == "table") and local_cfg or {}

-- "eDP-1" is a generic DRM connector class for a laptop's built-in panel, not
-- a machine-specific identity -- safe to hardcode across any laptop this repo
-- runs on. On a desktop with no eDP output (this rule matches nothing there)
-- the fallback rule below picks up the real monitor generically instead.
-- M.monitors, when present and non-empty, replaces both of these outright --
-- see local.lua's template comment for the shape. (Non-empty, not just
-- present: the template ships an uncommented-but-empty `monitors = {}`, and
-- an empty Lua table is still truthy.)
if M.monitors and #M.monitors > 0 then
    for _, m in ipairs(M.monitors) do
        hl.monitor(m)
    end
else
    hl.monitor({
        output   = "eDP-1",
        mode     = "preferred",
        position = "auto",
        scale    = 1,
    })

    -- Fallback for any other output (desktops, or external monitors on a laptop).
    hl.monitor({
        output   = "",
        mode     = "preferred",
        position = "auto",
        scale    = 1,
    })
end


-- Accent from the wallpaper (generated by matugen). Mutate this table below the
-- dofile() to override any of it.
local colors = dofile(os.getenv("HOME") .. "/dotfiles/hypr/colors.lua")

local terminal    = "kitty"
local fileManager = "kitty ranger -r ~/dotfiles/ranger"
local dotfiles    = os.getenv("HOME") .. "/dotfiles"


-- Everything is prefixed with `uwsm app --` so it gets its own systemd unit
-- instead of becoming a child of wayland-wm@hyprland.desktop.service. The
-- Hyprland wiki (Useful-Utilities/Systemd-start) recommends this under UWSM:
-- a crashing helper then cannot take the compositor's unit down with it.
local function app(cmd)
    hl.exec_cmd("uwsm app -- " .. cmd)
end

hl.on("hyprland.start", function()
    -- GTK4/libadwaita and the GTK portal read gsettings, not gtk-4.0/settings.ini.
    -- Without this, file dialogs and GNOME apps stay light on a dark desktop.
    hl.exec_cmd(dotfiles .. "/hypr/scripts/gsettings-theme.sh")

    -- Bar, dashboard corner and notifications all live in one quickshell
    -- instance now -- see quickshell/shell.qml. mako is retired: its
    -- NotificationServer would fight quickshell's for the
    -- org.freedesktop.Notifications D-Bus name if both ran. -n makes this a
    -- no-op if an instance is already running, so a config reload never
    -- stacks two of them.
    app("qs -d -n")
    -- Wallpaper: mpvpaper via wallpaper-daemon.sh, not hyprpaper. The wallpaper
    -- is a looping video (Disco-Elysium-4k.mp4) and hyprpaper only does stills;
    -- mpvpaper covers stills too, so it is the only wallpaper daemon now.
    -- The script reads hypr/wallpaper.conf, written by set-wallpaper.sh.
    -- On for machines by default; set `autostart = { wallpaper = false }` in
    -- local.lua for a machine that doesn't use a video/mpvpaper wallpaper --
    -- otherwise wallpaper-daemon.sh nags with a "mpvpaper is not installed"
    -- notification every login.
    if M.autostart == nil or M.autostart.wallpaper ~= false then
        hl.exec_cmd(dotfiles .. "/hypr/scripts/wallpaper-daemon.sh")
    end
    -- hypridle: disabled by default (no idle timeouts / auto-lock). Its config
    -- stays at hypr/hypridle.conf either way. Re-enable per machine with
    -- `autostart = { hypridle = true }` in local.lua.
    if M.autostart and M.autostart.hypridle then
        app("hypridle")
    end
    -- nm-applet retired: the bar's network module + Network panel (SUPER+N)
    -- replace it, and the tray it rendered into was disabled anyway
    -- (waybar's tray module was commented out).

    -- Polkit agent: NOT started here. hyprpolkitagent ships its own systemd user
    -- unit (WantedBy=graphical-session.target), which is the right mechanism
    -- under UWSM -- enabled once with:
    --   systemctl --user enable --now hyprpolkitagent.service
    -- Its binary lives at /usr/lib/hyprpolkitagent/, not on $PATH, so a
    -- `command -v` guard here would silently fall through to polkit-gnome.

    -- A permanent 3000K filter. wlsunset needed `-T 3001 -t 3000` (a 1-Kelvin
    -- gap) to fake that; hyprsunset does it directly and is runtime-adjustable
    -- via `hyprctl hyprsunset temperature <k>`.
    hl.exec_cmd("sh -c 'command -v hyprsunset >/dev/null "
        .. "&& exec uwsm app -- hyprsunset -t 3000 "
        .. "|| exec uwsm app -- wlsunset -T 3001 -t 3000'")

    -- Clipboard: cliphist stores history, wl-clip-persist keeps the selection
    -- alive after the source window closes (a Wayland-specific papercut).
    hl.exec_cmd("sh -c 'command -v cliphist >/dev/null && { "
        .. "uwsm app -- wl-paste --type text --watch cliphist store & "
        .. "uwsm app -- wl-paste --type image --watch cliphist store & }'")
    hl.exec_cmd("sh -c 'command -v wl-clip-persist >/dev/null "
        .. "&& exec uwsm app -- wl-clip-persist --clipboard regular'")
end)



hl.layer_rule({
    match        = { namespace = "quickshell-bar" },
    blur         = true,
    ignore_alpha = 0.2,
})

-- quickshell notification toasts, styled to match the bar pills, get the
-- same blur mako's did.
hl.layer_rule({
    match        = { namespace = "quickshell-notifications" },
    blur         = true,
    ignore_alpha = 0.2,
})

-- SUPER+G's system-info overlay -- on the `overlay` layer now (shows above
-- normal windows, not just the desktop), on demand only. Same 0xD9 surface
-- as the bar, so the same ignore_alpha.
hl.layer_rule({
    match        = { namespace = "quickshell-dashboard" },
    blur         = true,
    ignore_alpha = 0.2,
})

-- SUPER+I's ask-a-quick-question overlay -- same treatment as the dashboard.
hl.layer_rule({
    match        = { namespace = "quickshell-ask" },
    blur         = true,
    ignore_alpha = 0.2,
})

-- The ported rofi menus (launcher, clipboard, wallpaper, power, exit,
-- monitor) -- this replaces the `namespace = "rofi"` rule that used to sit
-- above, since they are layer surfaces for the same reason rofi was.
hl.layer_rule({
    match        = { namespace = "quickshell-menu" },
    blur         = true,
    ignore_alpha = 0.2,
})

-- The bar's dropdown panels (calendar, Wi-Fi, bluetooth, audio) -- same
-- surface as the menus above (quickshell/ui/Surface.qml), so same blur.
hl.layer_rule({
    match        = { namespace = "quickshell-panel" },
    blur         = true,
    ignore_alpha = 0.2,
})


hl.config({
    general = {
        gaps_in  = 5,
        -- The quickshell bar floats with margin-top/side from Theme.qml
        -- (barMarginTop 6, barMarginSide 8, both scaled by local.conf's
        -- UI_SCALE); matching that here keeps windows off the screen edge so
        -- the detached bar reads as deliberate rather than as a bar
        -- overlapping full-bleed windows. M.gaps_out overrides outright if
        -- Theme's derived margin ever needs a different gap.
        gaps_out = M.gaps_out or 8,

        -- was 0, which made the col.* accent below dead config: the
        -- wallpaper-derived accent showed on the bar, the menus and
        -- notifications but never on the focused window.
        border_size = 2,

        col = {
            -- gradient accent -> accent_dim; both come from the wallpaper.
            active_border   = {
                colors = { "rgba(" .. colors.accent .. "ff)",
                           "rgba(" .. colors.accent_dim .. "ff)" },
                angle  = 45,
            },
            inactive_border = "rgba(3C4449ff)",
        },

        resize_on_border = false,
        allow_tearing    = false,

        layout = "dwindle",
    },

    decoration = {
        -- 12px is the radius shared by the quickshell bar pills, notification
        -- toasts, the quickshell menu cards and the hyprlock input field.
        -- 3 was the odd one out.
        rounding = 12,
        active_opacity   = 1.0,
        inactive_opacity = 0.8,

        -- Shadows are on but scoped: the "no-shadow-when-tiled" window rule
        -- below turns them off for tiled windows, where every tile having a
        -- drop shadow just muddies the gaps. Floating windows and dialogs keep
        -- them, which is where the depth actually helps.
        shadow = {
            enabled       = true,
            range         = 20,
            render_power  = 3,
            offset        = "0 4",
            color         = "rgba(0A0F12AA)",
            color_inactive = "rgba(0A0F1266)",
        },

        blur = {
            enabled = true,
        },
    },

    animations = {
        enabled = true,
    },

    group = {
        col = {
            border_active   = "rgba(" .. colors.accent .. "ff)",
            border_inactive = "rgba(3C4449ff)",
        },
        groupbar = {
            font_family = "MesloLGS NF",
            font_size   = 11,
            -- match the quickshell bar pills: 12px radius, accent indicator, some air
            height           = 20,
            indicator_height = 3,
            rounding         = 12,
            gradient_rounding = 12,
            gaps_in          = 2,
            gaps_out         = 2,
            text_color       = "rgba(93A1A1ff)",
            col = {
                active   = "rgba(" .. colors.accent .. "ff)",
                inactive = "rgba(141C21ff)",
            },
        },
    },

    dwindle = {
        preserve_split = true,
    },

    misc = {
        force_default_wallpaper = 0,
        disable_hyprland_logo   = true,
        disable_splash_rendering = true,

        enable_swallow = true,
        swallow_regex  = "^(kitty)$",
    },
})

-- Default curves and animations
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 238.1191, dampening = 24.21279333 })

hl.animation({ leaf = "global",     enabled = true, speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",     enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",    enabled = true, speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn",  enabled = true, speed = 4.1,  spring = "easy",         style = "popin 87%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fade",       enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",     enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })


hl.config({
    input = {
        kb_layout  = M.kb_layout or "us,ru",
        kb_options = "grp:shifts_toggle",

        follow_mouse = 1,
        sensitivity  = 0,

        touchpad = {
            natural_scroll = false,
        },
    },
})

hl.gesture({
    fingers   = 3,
    direction = "horizontal",
    action    = "workspace",
})


local mainMod = "SUPER"

---- Launchers and terminal -------------------------------------------------
hl.bind(mainMod .. " + Return",  hl.dsp.exec_cmd(terminal),   { description = "Terminal" })
hl.bind(mainMod .. " + End",     hl.dsp.exec_cmd(terminal),   { description = "Terminal" })
hl.bind(mainMod .. " + Q", hl.dsp.window.close(),     { description = "Close window" })
hl.bind(mainMod .. " + E",       hl.dsp.exec_cmd(fileManager), { description = "File manager" })

-- SUPER+Z (rofi's `run` mode) is deliberately gone: it went unused, and the
-- launcher below covers what it was for.
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd("qs ipc call menu toggle launcher"), {
	description = "App launcher",
})
-- Network/bluetooth/audio now open the quickshell panels instead of
-- launching a separate rofi/GTK tool -- see quickshell/panels/.
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd("qs ipc call panel toggle network"), {
	description = "Network menu",
})
hl.bind(mainMod .. " + Y", hl.dsp.exec_cmd("qs ipc call panel toggle bluetooth"), {
	description = "Bluetooth menu",
})
hl.bind(mainMod .. " + P", hl.dsp.exec_cmd("qs ipc call panel toggle audio"), {
	description = "Audio menu",
})
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd("qs ipc call menu toggle power"), {
	description = "Power menu",
})
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("qs ipc call menu toggle monitor"), {
	description = "Monitor placement",
})
hl.bind(mainMod .. " + G", hl.dsp.exec_cmd("qs ipc call dashboard toggle"), {
	description = "Toggle system info overlay",
})
hl.bind(mainMod .. " + I", hl.dsp.exec_cmd("qs ipc call ask toggle"), {
	description = "Ask AI a quick question",
})

---- Focus and movement -----------------------------------------------------
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + SHIFT + left",  hl.dsp.window.move({ direction = "left" }))
hl.bind(mainMod .. " + SHIFT + down",  hl.dsp.window.move({ direction = "down" }))
hl.bind(mainMod .. " + SHIFT + up",    hl.dsp.window.move({ direction = "up" }))
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.move({ direction = "right" }))

---- Layout -----------------------------------------------------------------
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen(),                { description = "Fullscreen" })
hl.bind(mainMod .. " + SHIFT + space", hl.dsp.window.float({ action = "toggle" }), { description = "Toggle floating" })
hl.bind(mainMod .. " + space", hl.dsp.window.cycle_next(),            { description = "Cycle windows" })

hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"), { description = "Toggle split direction" })

-- i3's stacking layout -> Hyprland groups (tabbed groupbar).
--
-- Grouping here is directional and purely additive: no keystroke toggles a
-- group, so none can implode one by accident. SUPER+S is the sole destructive
-- key and is guarded below so it can only ever dissolve, never create.
hl.bind(mainMod .. " + A", hl.dsp.group.prev(), { description = "Previous in group" })
hl.bind(mainMod .. " + Q", hl.dsp.group.next(), { description = "Next in group" })

-- group.toggle() maps to togglegroup, which is symmetric: it creates a group
-- on an ungrouped window and destroys the whole group on a grouped one. That
-- second half was the accident -- one stray SUPER+S scattered a stack that
-- then had to be rebuilt window by window. Bound raw it is also useless now
-- that merging is directional, since creating a group of one achieves nothing.
-- So: dissolve when there is something to dissolve, otherwise do nothing.
hl.bind(mainMod .. " + S", function()
	local w = hl.get_active_window()
	if w and w.group then
		hl.dispatch(hl.dsp.group.toggle())
	end
end, { description = "Dissolve group" })

-- SUPER+CTRL+<dir> is the third rung of the ladder that starts at
-- SUPER+<dir> (focus it) and SUPER+SHIFT+<dir> (move it): move the active
-- window in that direction *and* merge it with whatever is there, creating
-- the group on the fly when the neighbour is a plain window.
--
-- Hyprland ships no dispatcher for that last part. `moveintogroup <dir>`
-- merges only into a target that is ALREADY a group and silently no-ops
-- against a plain window; `movewindoworgroup` (what this key used to be)
-- degrades to a plain move in the same case. Neither can promote a neighbour,
-- so the "group it first, then merge" half has to live in Lua.
--
-- Finding the neighbour: there is no "window in direction X" query either, so
-- this borrows Hyprland's own logic -- dispatch focus(dir), read back the
-- active window, restore focus. That guarantees SUPER+CTRL+left merges with
-- exactly the window SUPER+left would have focused, rather than a second
-- adjacency rule that drifts from it. The whole round-trip runs inside one
-- bind handler, so no intermediate focus state is ever painted.
--
-- Only the active window moves, never its whole group -- the same scope as
-- SUPER+SHIFT+<dir>. group:auto_group stays true, so windows spawned later
-- still join the focused group on their own.
local function merge_into(dir)
	return function()
		local a = hl.get_active_window()
		if not a or a.floating then return end

		-- Walk to the neighbour, note it, come straight back.
		hl.dispatch(hl.dsp.focus({ direction = dir }))
		local b = hl.get_active_window()
		hl.dispatch(hl.dsp.focus({ window = a }))

		-- Bounced off the edge of the layout: nothing in that direction.
		if not b or b.address == a.address then return end
		-- Floating windows sit outside the tiling layout; a group of one
		-- tiled and one floating window is not worth having.
		if b.floating then return end
		-- movefocus happily crosses a monitor edge, but a group cannot span
		-- two monitors -- stop at the edge rather than teleport the window.
		if tostring(b.monitor) ~= tostring(a.monitor) then return end
		-- Focus cycled within our own group instead of leaving it (see
		-- binds:movefocus_cycles_groupfirst) -- already siblings, nothing to do.
		if a.group and b.group and tostring(a.group) == tostring(b.group) then return end

		-- Plain neighbour: promote it to a group of one so there is something
		-- to merge into. togglegroup acts on the focused window, so hand it
		-- focus for exactly that one call.
		if not b.group then
			hl.dispatch(hl.dsp.focus({ window = b }))
			hl.dispatch(hl.dsp.group.toggle())
			b = hl.get_active_window()
			hl.dispatch(hl.dsp.focus({ window = a }))
			if not (b and b.group) then return end
		end

		-- Leave the old group before joining the new one: group:add is
		-- documented to add a window, not to migrate one between groups.
		if a.group then
			hl.dispatch(hl.dsp.window.move({ out_of_group = true }))
			a = hl.get_active_window()
			if not a then return end
		end

		b.group:add(a)
		hl.dispatch(hl.dsp.focus({ window = a }))
	end
end

hl.bind(mainMod .. " + CTRL + left",  merge_into("left"), {
	description = "Merge window into group (left)",
})
hl.bind(mainMod .. " + CTRL + right", merge_into("right"), {
	description = "Merge window into group (right)",
})
hl.bind(mainMod .. " + CTRL + up",    merge_into("up"), {
	description = "Merge window into group (up)",
})
hl.bind(mainMod .. " + CTRL + down",  merge_into("down"), {
	description = "Merge window into group (down)",
})

-- The only way out of a group, and the only way to shrink one: pops the
-- active window out regardless of what is next to it. Repeat it to empty a
-- group one window at a time; SUPER+S above does it in a single stroke.
hl.bind(mainMod .. " + SHIFT + A",    hl.dsp.window.move({ out_of_group = true }), {
	description = "Move out of group",
})

---- Workspaces -------------------------------------------------------------
local wsKeys = { "1", "2", "3", "4", "5", "6", "7", "8", "9", "0" }
for i, key in ipairs(wsKeys) do
    local ws = i  -- key "0" is workspace 10
    hl.bind(mainMod .. " + " .. key,            hl.dsp.focus({ workspace = ws }))
    hl.bind(mainMod .. " + CTRL + " .. key,     hl.dsp.window.move({ workspace = ws, silent = true }))
    hl.bind(mainMod .. " + SHIFT + " .. key,    hl.dsp.window.move({ workspace = ws }))
end

hl.bind(mainMod .. " + B",         hl.dsp.focus({ workspace = "previous" }), { description = "Back and forth" })
hl.bind(mainMod .. " + CTRL + B",  hl.dsp.window.move({ workspace = "previous", silent = true }))
hl.bind(mainMod .. " + SHIFT + B", hl.dsp.window.move({ workspace = "previous" }))

hl.bind(mainMod .. " + Tab",         hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + SHIFT + Tab", hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- i3's floating_modifier. `{ mouse = true }` is correct here -- it matches
-- upstream's own example/hyprland.lua. Note `hyprctl binds` prints these under a
-- plain `bind` header rather than `bindm`; that is a reporting quirk, not a bug.
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

---- Session ----------------------------------------------------------------
hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd("hyprctl reload"), { description = "Reload config" })
hl.bind(mainMod .. " + SHIFT + E", hl.dsp.exec_cmd("qs ipc call menu toggle exit"),
    { description = "Exit Hyprland (confirm)" })

---- Resize submap (i3's `mode "resize"`) -----------------------------------
hl.define_submap("resize", function()
    hl.bind("left",  hl.dsp.window.resize({ x = -10, y = 0, relative = true }), { repeating = true })
    hl.bind("right", hl.dsp.window.resize({ x = 10, y = 0, relative = true }),  { repeating = true })
    hl.bind("up",    hl.dsp.window.resize({ x = 0, y = -10, relative = true }), { repeating = true })
    hl.bind("down",  hl.dsp.window.resize({ x = 0, y = 10, relative = true }),  { repeating = true })

    hl.bind("Return", hl.dsp.submap("reset"))
    hl.bind("Escape", hl.dsp.submap("reset"))
    hl.bind(mainMod .. " + R", hl.dsp.submap("reset"))
end)
hl.bind(mainMod .. " + R", hl.dsp.submap("resize"), { description = "Resize mode" })

---- Media and hardware keys (unchanged commands from i3) -------------------
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ +2%"),
	{ locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ -2%"),
	{ locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("pactl set-sink-mute @DEFAULT_SINK@ toggle"), { locked = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("pactl set-source-mute @DEFAULT_SOURCE@ toggle"), { locked = true })

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"),   { locked = true })

hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd("brightnessctl set 10%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 10%-"), { locked = true, repeating = true })

---- Wallpaper -------------------------------------------------------------
-- The picker is quickshell's -- a carousel showing each wallpaper with the
-- colour scheme it would generate; set-wallpaper.sh still does the work once
-- a file is chosen (ffmpeg frame-grab for videos, matugen, mpvpaper/swww).
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("qs ipc call menu toggle wallpaper"),
    { description = "Pick wallpaper (regenerates accent)" })

---- Clipboard --------------------------------------------------------------
-- cliphist is still the store; only the picker in the middle changed.
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd("qs ipc call menu toggle clipboard"),
    { description = "Clipboard history" })

---- Scratchpad -------------------------------------------------------------
-- Native special workspace; no pyprland needed for the single-terminal case.
hl.bind(mainMod .. " + U", hl.dsp.workspace.toggle_special({ name = "scratch" }),
    { description = "Toggle scratchpad" })
hl.bind(mainMod .. " + SHIFT + U",
    hl.dsp.window.move({ workspace = "special:scratch" }),
    { description = "Send window to scratchpad" })

hl.workspace_rule({
    workspace = "special:scratch",
    on_created_empty = terminal,
    gaps_out = 60,
})

---- Screenshots ------------------------------------------------------------
-- i3: Print -> i3-scrot (fullscreen), Shift+Print -> scrot.sh (region select via `import`)
-- The script picks hyprshot when installed and falls back to grim/slurp.
local shot = dotfiles .. "/hypr/scripts/screenshot.sh "
hl.bind("Print",                    hl.dsp.exec_cmd(shot .. "full"),   { description = "Screenshot: whole screen" })
hl.bind("SHIFT + Print",            hl.dsp.exec_cmd(shot .. "region"), { description = "Screenshot: region" })
hl.bind(mainMod .. " + Print",      hl.dsp.exec_cmd(shot .. "window"), { description = "Screenshot: pick a window" })
hl.bind("ALT + Print",              hl.dsp.exec_cmd(shot .. "active"), { description = "Screenshot: focused window" })
hl.bind("CTRL + Print",             hl.dsp.exec_cmd(shot .. "edit"), {
	description = "Screenshot: region -> annotate",
})
hl.bind(mainMod .. " + SHIFT + Print", hl.dsp.exec_cmd(shot .. "clip"), {
	description = "Screenshot: region -> clipboard only",
})


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- Workspace -> monitor assignment, mirroring i3's `workspace N output`.
-- M.workspaces, when present, is a list of { first, last, monitor } ranges --
-- see local.lua's template comment. Without it (single-monitor boxes, or a
-- fresh clone before local.lua is edited), workspaces 1-5 default to "eDP-1"
-- (the same generic laptop-panel connector class as the monitor rule above:
-- on a desktop with no eDP-1 the rule just never matches) and 6-10 are left
-- unpinned rather than hardcoded to any one external monitor's description.
if M.workspaces and #M.workspaces > 0 then
    for _, w in ipairs(M.workspaces) do
        for i = w[1], w[2] do
            hl.workspace_rule({ workspace = tostring(i), monitor = w[3] })
        end
    end
else
    for i = 1, 5 do
        hl.workspace_rule({ workspace = tostring(i), monitor = "eDP-1" })
    end
end

-- Terminals: solid-ish when focused, noticeably see-through when not.
-- kitty's own `background_opacity` is left at 1.0 so these two numbers are the whole story.
hl.window_rule({
    name    = "kitty-opacity",
    match   = { class = "(?i)^kitty$" },
    opacity = "0.95 0.85",
})

-- Shadow only where it adds depth. A tiled grid of shadowed windows reads as
-- noise in the 8px gaps; a floating dialog over them reads as lifted.
hl.window_rule({
    name      = "no-shadow-when-tiled",
    match     = { float = false },
    no_shadow = true,
})

hl.window_rule({
    name     = "no-focus-popups",
    match    = { title = "(?i)pop-up" },
    no_focus = true,
})

hl.window_rule({
    name           = "suppress-maximize-events",
    match          = { class = ".*" },
    suppress_event = "maximize",
})

hl.window_rule({
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },
    no_focus = true,
})

-- ripdrag is the drag source ranger cannot be (<C-g> in ranger/rc.conf): a
-- throwaway GTK4 window that exists for the few seconds between picking a file
-- and dropping it onto the browser. Tiling it would reflow the whole layout
-- mid-drag, so it floats; it is pinned because dragging across a workspace
-- switch would otherwise leave it behind.
--
-- Class is the GTK app-id `it.catboy.ripdrag`, NOT `ripdrag` -- confirmed with
-- `hyprctl clients`; a `^ripdrag$` match silently never fires.
--
-- No `size` or `move` here, deliberately, both tested and rejected:
--   * `size` loses to GTK -- ripdrag's window is non-resizable (no --resizable),
--     so it renders at its own size regardless. Size it with ripdrag's own
--     -W/-H in ranger/rc.conf instead, which is where it actually takes.
--   * `move = "cursor <dx> <dy>"` is not understood by the Lua rule parser --
--     the window silently falls back to centred. Absolute `move = "x y"` does
--     work, but lands ~50/80px off the requested spot and would need per-monitor
--     numbers. Centred is predictable, and the pad is small enough (240x180)
--     to grab and drag off the browser without covering much of it.
hl.window_rule({
    name  = "ripdrag-drag-pad",
    match = { class = "(?i)^it\\.catboy\\.ripdrag$" },
    float = true,
    pin   = true,
})
