local function cursor_theme()
    for _, name in ipairs({ "Bibata-Modern-Ice", "Bibata-Modern-Classic" }) do
        for _, dir in ipairs({ "/usr/share/icons/", os.getenv("HOME") .. "/.local/share/icons/",
                               os.getenv("HOME") .. "/.icons/" }) do
            local f = io.open(dir .. name .. "/index.theme", "r")
            if f then f:close(); return name end
        end
    end
    return "Adwaita"
end

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("XCURSOR_THEME", cursor_theme())


local ok, local_cfg = pcall(dofile, os.getenv("HOME") .. "/.config/dotfiles/local.lua")
local M = (ok and type(local_cfg) == "table") and local_cfg or {}

-- The flat KEY=value sibling (configure.sh): keyboard layout and autostarts.
local C = {}
do
    local f = io.open(os.getenv("HOME") .. "/.config/dotfiles/local.conf", "r")
    if f then
        for line in f:lines() do
            local k, v = line:match("^%s*([%w_]+)%s*=%s*(.-)%s*$")
            if k then C[k] = v end
        end
        f:close()
    end
end
local function conf_bool(key, default)
    local v = C[key]
    if v == nil or v == "" then return default end
    return v ~= "0" and v:lower() ~= "false"
end

local monitors = M.monitors and #M.monitors > 0 and M.monitors or {
    { output = "eDP-1", mode = "preferred", position = "auto", scale = 1 },
    -- Fallback for any other output (desktops, or external monitors on a laptop).
    { output = "",      mode = "preferred", position = "auto", scale = 1 },
}
for _, m in ipairs(monitors) do
    hl.monitor(m)
end

local function restore_monitor_layout()
    hl.exec_cmd("python3 " .. os.getenv("HOME") .. "/dotfiles/hypr/scripts/monitor-layout.py --restore")
end
for _, event in ipairs({ "hyprland.start", "config.reloaded", "monitor.added", "monitor.removed" }) do
    hl.on(event, restore_monitor_layout)
end

-- Wallpaper accent plus the fixed base from matugen/base.json, generated by
-- matugen. Laid over the committed snapshot in matugen/defaults/, so a
-- generated file older than a newly added key (or missing outright) still
-- yields a complete table. Mutate it below to override anything.
local colors = dofile(os.getenv("HOME") .. "/dotfiles/matugen/defaults/hypr/colors.lua")
local gen_ok, generated = pcall(dofile, os.getenv("HOME") .. "/dotfiles/hypr/colors.lua")
if gen_ok and type(generated) == "table" then
    for k, v in pairs(generated) do colors[k] = v end
end

local terminal    = "kitty"
local dotfiles    = os.getenv("HOME") .. "/dotfiles"


local function app(cmd)
    hl.exec_cmd("uwsm app -- " .. cmd)
end

hl.on("hyprland.start", function()
    -- GTK4/libadwaita and the GTK portal read gsettings, not gtk-4.0/settings.ini.
    -- Without this, file dialogs and GNOME apps stay light on a dark desktop.
    hl.exec_cmd(dotfiles .. "/hypr/scripts/gsettings-theme.sh")

    app("qs -d -n")
    if conf_bool("AUTOSTART_WALLPAPER", true) then
        hl.exec_cmd(dotfiles .. "/hypr/scripts/wallpaper-daemon.sh")
    end
    if conf_bool("AUTOSTART_HYPRIDLE", false) then
        app("hypridle")
    end
    hl.exec_cmd("sh -c 'command -v hyprsunset >/dev/null "
        .. "&& exec uwsm app -- hyprsunset -t 3000 "
        .. "|| exec uwsm app -- wlsunset -T 3001 -t 3000'")

    hl.exec_cmd("sh -c 'command -v cliphist >/dev/null && { "
        .. "uwsm app -- wl-paste --type text --watch cliphist store & "
        .. "uwsm app -- wl-paste --type image --watch cliphist store & }'")
    hl.exec_cmd("sh -c 'command -v wl-clip-persist >/dev/null "
        .. "&& exec uwsm app -- wl-clip-persist --clipboard regular'")
end)



for _, ns in ipairs({ "bar", "notifications", "dashboard", "ask", "menu", "panel", "osd", "keymap" }) do
    hl.layer_rule({
        match        = { namespace = "quickshell-" .. ns },
        -- keymap stays unblurred so what you type underneath stays readable.
        blur         = ns ~= "keymap",
        ignore_alpha = 0.2,
        -- quickshell/ui/Reveal.qml animates these surfaces itself.
        no_anim      = ns ~= "bar" and ns ~= "notifications" or nil,
    })
end

hl.config({
    general = {
        gaps_in  = 5,
        gaps_out = M.gaps_out or 8,
        border_size = 2,
        col = {
            active_border   = {
                colors = { "rgba(" .. colors.accent .. "ff)",
                           "rgba(" .. colors.accent_dim .. "ff)" },
                angle  = 45,
            },
            inactive_border = "rgba(" .. colors.border .. "ff)",
        },

        resize_on_border = false,
        allow_tearing    = false,

        layout = "dwindle",
    },

    decoration = {
        rounding = 12,
        active_opacity   = 1.0,
        inactive_opacity = 0.8,
        shadow = {
            enabled       = true,
            range         = 20,
            render_power  = 3,
            offset        = "0 4",
            color         = "rgba(" .. colors.shadow .. "AA)",
            color_inactive = "rgba(" .. colors.shadow .. "66)",
        },

        blur = {
            enabled = true,
        },
    },

    animations = {
        enabled = true,
    },

    group = {
        col = {
            border_active   = "rgba(" .. colors.accent .. "ff)",
            border_inactive = "rgba(" .. colors.border .. "ff)",
        },
        groupbar = {
            font_family = "MesloLGS NF",
            font_size   = 11,
            height           = 20,
            indicator_height = 3,
            rounding         = 12,
            gradient_rounding = 12,
            gaps_in          = 2,
            gaps_out         = 2,
            text_color       = "rgba(" .. colors.fg .. "ff)",
            col = {
                active   = "rgba(" .. colors.accent .. "ff)",
                inactive = "rgba(" .. colors.bg .. "ff)",
            },
        },
    },

    dwindle = {
        preserve_split = true,
    },

    misc = {
        force_default_wallpaper = 0,
        disable_hyprland_logo   = true,
        disable_splash_rendering = true,

        enable_swallow = true,
        swallow_regex  = "^(kitty)$",
    },
})

-- Default curves and animations
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 238.1191, dampening = 24.21279333 })

hl.animation({ leaf = "global",     enabled = true, speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",     enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",    enabled = true, speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn",  enabled = true, speed = 4.1,  spring = "easy",         style = "popin 87%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fade",       enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",     enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })


hl.config({
    input = {
        -- graphite: xkb/symbols/graphite (not in xkeyboard-config). us stays
        -- first so binds resolve by qwerty position on every layout.
        kb_layout  = (C.KB_LAYOUT ~= "" and C.KB_LAYOUT) or "us,ru,graphite",
        kb_options = "grp:shifts_toggle",

        follow_mouse = 1,
        sensitivity  = 0,

        touchpad = {
            natural_scroll = false,
        },
    },
})

hl.gesture({
    fingers   = 3,
    direction = "horizontal",
    action    = "workspace",
})


local mainMod = "SUPER"

---- Launchers and terminal -------------------------------------------------
hl.bind(mainMod .. " + Return",  hl.dsp.exec_cmd(terminal),   { description = "Terminal" })
hl.bind(mainMod .. " + End",     hl.dsp.exec_cmd(terminal),   { description = "Terminal" })
hl.bind(mainMod .. " + X", hl.dsp.window.close(),     { description = "Close window" })

-- SUPER+Z (rofi's `run` mode) is deliberately gone: it went unused, and the
-- launcher covers what it was for.
--
-- The top row (Q..P) is workspaces, so what used to live there -- bluetooth,
-- audio, wallpaper, ask, resize, reload -- plus monitors, media, power and
-- the app launcher is one quickshell menu (quickshell/panels/Hub.qml):
-- SUPER+D, then a letter; `d` again searches apps, settings and actions
-- (quickshell/panels/Launcher.qml), 1-9, 0 launch the most-used apps.
-- `qs ipc call menu toggle launcher` still opens the search directly.
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd("qs ipc call menu toggle hub"), {
	description = "Menu (d search apps, 1-9/0 recent, letters open pages)",
})
-- Network/bluetooth/audio now open the quickshell panels instead of
-- launching a separate rofi/GTK tool -- see quickshell/panels/.
hl.bind(mainMod .. " + G", hl.dsp.exec_cmd("qs ipc call dashboard toggle"), {
	description = "Toggle system info overlay",
})
hl.bind(mainMod .. " + K", hl.dsp.exec_cmd("qs ipc call keymap toggle"), {
	description = "Toggle keyboard layout cheat sheet",
})
hl.bind(mainMod .. " + SHIFT + K", hl.dsp.exec_cmd("qs ipc call keymap shape"), {
	description = "Cheat sheet: switch between normal and TOTEM shape",
})
-- Also on the SUPER+D hub (c); the Lua API has no reload dispatcher.
hl.bind(mainMod .. " + C", hl.dsp.exec_cmd("hyprctl reload"), {
	description = "Reload Hyprland config",
})

---- Focus and movement -----------------------------------------------------
for _, dir in ipairs({ "left", "down", "up", "right" }) do
    hl.bind(mainMod .. " + " .. dir, hl.dsp.focus({ direction = dir }), { description = "Focus " .. dir })
    hl.bind(mainMod .. " + SHIFT + " .. dir, hl.dsp.window.move({ direction = dir }),
        { description = "Move window " .. dir })
end

---- Layout -----------------------------------------------------------------
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen(),                { description = "Fullscreen" })
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"), { description = "Toggle split direction" })
hl.bind(mainMod .. " + A", hl.dsp.group.prev(), { description = "Previous in group" })
hl.bind(mainMod .. " + S", hl.dsp.group.toggle(), { description = "Toggle group" })
local function merge_into(dir)
	return function()
		local a = hl.get_active_window()
		if not a or a.floating then return end

		-- Walk to the neighbour, note it, come straight back.
		hl.dispatch(hl.dsp.focus({ direction = dir }))
		local b = hl.get_active_window()
		hl.dispatch(hl.dsp.focus({ window = a }))

		-- Bounced off the edge of the layout: nothing in that direction.
		if not b or b.address == a.address then return end
		-- Floating windows sit outside the tiling layout; a group of one
		-- tiled and one floating window is not worth having.
		if b.floating then return end
		-- movefocus happily crosses a monitor edge, but a group cannot span
		-- two monitors -- stop at the edge rather than teleport the window.
		if tostring(b.monitor) ~= tostring(a.monitor) then return end
		-- Focus cycled within our own group instead of leaving it (see
		-- binds:movefocus_cycles_groupfirst) -- already siblings, nothing to do.
		if a.group and b.group and tostring(a.group) == tostring(b.group) then return end

		-- Plain neighbour: promote it to a group of one so there is something
		-- to merge into. togglegroup acts on the focused window, so hand it
		-- focus for exactly that one call.
		if not b.group then
			hl.dispatch(hl.dsp.focus({ window = b }))
			hl.dispatch(hl.dsp.group.toggle())
			b = hl.get_active_window()
			hl.dispatch(hl.dsp.focus({ window = a }))
			if not (b and b.group) then return end
		end

		-- Leave the old group before joining the new one: group:add is
		-- documented to add a window, not to migrate one between groups.
		if a.group then
			hl.dispatch(hl.dsp.window.move({ out_of_group = true }))
			a = hl.get_active_window()
			if not a then return end
		end

		b.group:add(a)
		hl.dispatch(hl.dsp.focus({ window = a }))
	end
end

for _, dir in ipairs({ "left", "right", "up", "down" }) do
    hl.bind(mainMod .. " + CTRL + " .. dir, merge_into(dir),
        { description = "Merge window into group (" .. dir .. ")" })
end
hl.bind(mainMod .. " + SHIFT + A",    hl.dsp.window.move({ out_of_group = true }), {
	description = "Move out of group",
})

---- Workspaces -------------------------------------------------------------
-- The letter row, not the number row: on a 38-key board the numbers sit
-- behind a layer, so SUPER+number was a three-key chord. Workspaces keep
-- their numeric ids (Q is 1 ... P is 10), so the workspace rules below are
-- unchanged; the bar pills show the letter (wsKeys in
-- quickshell/bar/modules/Workspaces.qml -- keep the two in sync).
local wsKeys = { "Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P" }
for i, key in ipairs(wsKeys) do
    local ws = i
    hl.bind(mainMod .. " + " .. key,            hl.dsp.focus({ workspace = ws }),
        { description = "Workspace " .. ws })
    hl.bind(mainMod .. " + CTRL + " .. key,     hl.dsp.window.move({ workspace = ws, silent = true }),
        { description = "Send window to workspace " .. ws .. " (stay)" })
    hl.bind(mainMod .. " + SHIFT + " .. key,    hl.dsp.window.move({ workspace = ws }),
        { description = "Move window to workspace " .. ws })
end

hl.bind(mainMod .. " + B",         hl.dsp.focus({ workspace = "previous" }), { description = "Back and forth" })
hl.bind(mainMod .. " + SHIFT + B", hl.dsp.window.move({ workspace = "previous" }),
    { description = "Move window to previous workspace" })

hl.bind(mainMod .. " + Tab",         hl.dsp.focus({ workspace = "e+1" }), { description = "Next workspace" })
hl.bind(mainMod .. " + SHIFT + Tab", hl.dsp.focus({ workspace = "e-1" }), { description = "Previous workspace" })

hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }), { description = "Next workspace" })
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }), { description = "Previous workspace" })

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true, description = "Drag window" })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true, description = "Resize window" })

---- Session ----------------------------------------------------------------
hl.bind("Escape", hl.dsp.exec_cmd("qs ipc call notifications dismiss"), {
    non_consuming = true,
    submap_universal = true,
    description = "Dismiss notifications",
})

---- Resize submap (i3's `mode "resize"`) -----------------------------------
-- Entered from the SUPER+D menu (r); SUPER+R is workspace 4 now.
hl.define_submap("resize", function()
    hl.bind("left",  hl.dsp.window.resize({ x = -10, y = 0, relative = true }),
        { repeating = true, description = "Narrower" })
    hl.bind("right", hl.dsp.window.resize({ x = 10, y = 0, relative = true }),
        { repeating = true, description = "Wider" })
    hl.bind("up",    hl.dsp.window.resize({ x = 0, y = -10, relative = true }),
        { repeating = true, description = "Shorter" })
    hl.bind("down",  hl.dsp.window.resize({ x = 0, y = 10, relative = true }),
        { repeating = true, description = "Taller" })

    hl.bind("Return", hl.dsp.submap("reset"), { description = "Leave resize mode" })
    hl.bind("Escape", hl.dsp.submap("reset"), { description = "Leave resize mode" })
end)

---- Media and hardware keys (unchanged commands from i3) -------------------
-- Volume stays on pactl: quickshell's OSD (ui/Osd.qml) watches Pipewire, so
-- it shows for these without being in the loop.
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ +2%"),
	{ locked = true, repeating = true, description = "Volume up" })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ -2%"),
	{ locked = true, repeating = true, description = "Volume down" })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("pactl set-sink-mute @DEFAULT_SINK@ toggle"),
	{ locked = true, description = "Mute" })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("pactl set-source-mute @DEFAULT_SOURCE@ toggle"),
	{ locked = true, description = "Mute microphone" })

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true, description = "Play / pause" })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"),       { locked = true, description = "Next track" })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"),   { locked = true, description = "Previous track" })

-- Through quickshell rather than brightnessctl directly: sysfs sends no event
-- on a backlight change, so the shell has to make the change to show the OSD
-- (quickshell/services/Brightness.qml).
hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd("qs ipc call brightness up"),
	{ locked = true, repeating = true, description = "Brightness up" })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("qs ipc call brightness down"),
	{ locked = true, repeating = true, description = "Brightness down" })

hl.bind(mainMod .. " + V", hl.dsp.exec_cmd("qs ipc call menu toggle clipboard"),
    { description = "Clipboard history" })

local shot = dotfiles .. "/hypr/scripts/screenshot.sh "
hl.bind("Print",                    hl.dsp.exec_cmd(shot .. "full"),   { description = "Screenshot: whole screen" })
hl.bind("SHIFT + Print",            hl.dsp.exec_cmd(shot .. "region"), { description = "Screenshot: region" })
hl.bind(mainMod .. " + Print",      hl.dsp.exec_cmd(shot .. "window"), { description = "Screenshot: pick a window" })
hl.bind("ALT + Print",              hl.dsp.exec_cmd(shot .. "active"), { description = "Screenshot: focused window" })
hl.bind("CTRL + Print",             hl.dsp.exec_cmd(shot .. "edit"), {
	description = "Screenshot: region -> annotate",
})
hl.bind(mainMod .. " + SHIFT + Print", hl.dsp.exec_cmd(shot .. "clip"), {
	description = "Screenshot: region -> clipboard only",
})
-- Screen recording (quickshell/services/Recorder.qml, wf-recorder). The same
-- bind stops it; so does clicking the red timer in the bar.
hl.bind(mainMod .. " + ALT + Print", hl.dsp.exec_cmd("qs ipc call recorder toggle region"), {
	description = "Record region (again to stop)",
})
hl.bind(mainMod .. " + ALT + SHIFT + Print", hl.dsp.exec_cmd("qs ipc call recorder toggle screen"), {
	description = "Record screen (again to stop)",
})


if M.workspaces and #M.workspaces > 0 then
    for _, w in ipairs(M.workspaces) do
        for i = w[1], w[2] do
            hl.workspace_rule({ workspace = tostring(i), monitor = w[3] })
        end
    end
else
    -- 1-10 are split across the screens in reading order: rows top to bottom
    -- (screens whose vertical spans overlap share a row), left to right
    -- within a row. Uneven splits give the extra workspace to the earlier
    -- screens, so four in a square get 1-3 4-6 / 7-8 9-10. Rules only take a
    -- fixed monitor, so they are rebuilt (and existing workspaces moved) on
    -- every hotplug / layout change. Mirrors don't count as a separate screen.
    local ws_rules = {}
    local function distribute_workspaces()
        for _, rule in ipairs(ws_rules) do rule:set_enabled(false) end
        ws_rules = {}

        local screens = {}
        for _, m in ipairs(hl.get_monitors()) do
            if not m.is_mirror then
                local s = (m.scale and m.scale > 0) and m.scale or 1
                screens[#screens + 1] = { name = m.name, x = m.x, y = m.y, b = m.y + m.height / s }
            end
        end
        if #screens == 0 then return end

        table.sort(screens, function(a, b) return a.y < b.y or (a.y == b.y and a.x < b.x) end)
        local rows = {}
        for _, s in ipairs(screens) do
            local row = rows[#rows]
            if row and s.y < row.b then row[#row + 1] = s
            else rows[#rows + 1] = { s, b = s.b } end
        end
        local order = {}
        for _, row in ipairs(rows) do
            table.sort(row, function(a, b) return a.x < b.x end)
            for _, s in ipairs(row) do order[#order + 1] = s.name end
        end

        local n = #order
        local ws = 1
        for i, name in ipairs(order) do
            local count = 10 // n + (i <= 10 % n and 1 or 0)
            for _ = 1, count do
                local id = tostring(ws)
                ws_rules[#ws_rules + 1] = hl.workspace_rule({ workspace = id, monitor = name })
                local existing = hl.get_workspace(id)
                if existing and existing.monitor and existing.monitor.name ~= name then
                    hl.dispatch(hl.dsp.workspace.move({ workspace = id, monitor = name }))
                end
                ws = ws + 1
            end
        end
    end
    -- Deferred so the event's layout (and monitor-layout.py --restore) settles first.
    local function schedule_distribute()
        hl.timer(distribute_workspaces, { timeout = 500, type = "oneshot" })
    end
    for _, event in ipairs({ "hyprland.start", "config.reloaded", "monitor.added",
                             "monitor.removed", "monitor.layout_changed" }) do
        hl.on(event, schedule_distribute)
    end
end

hl.window_rule({
    name    = "kitty-opacity",
    match   = { class = "(?i)^kitty$" },
    opacity = "0.95 0.85",
})

hl.window_rule({
    name      = "no-shadow-when-tiled",
    match     = { float = false },
    no_shadow = true,
})

hl.window_rule({
    name     = "no-focus-popups",
    match    = { title = "(?i)pop-up" },
    no_focus = true,
})

hl.window_rule({
    name           = "suppress-maximize-events",
    match          = { class = ".*" },
    suppress_event = "maximize",
})

hl.window_rule({
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },
    no_focus = true,
})

hl.window_rule({
    name  = "ripdrag-drag-pad",
    match = { class = "(?i)^it\\.catboy\\.ripdrag$" },
    float = true,
    pin   = true,
})
