pragma Singleton

// GENERATED BY MATUGEN -- DO NOT EDIT. Regenerate: hypr/scripts/set-wallpaper.sh
// Distinct module hues are harmonized toward the wallpaper, like the prompt.
import QtQuick
import Quickshell

Singleton {
    readonly property color accent: "#acc7ff"
    readonly property color accentAlt: "#cabff8"
    readonly property color accentDim: "#004591"
    readonly property color urgent: "#ffb4ab"
    readonly property color red: "#ffb2b9"
    readonly property color orange: "#ffb597"
    readonly property color green: "#00e295"
    readonly property color cyan: "#00daf4"
    readonly property color blue: "#abc7ff"
    readonly property color purple: "#cbbeff"
    // Wallpaper-tinted dark surface -- for hovered/selected backgrounds only.
    readonly property color surface: "#262a33"
}
