-- GENERATED BY MATUGEN -- DO NOT EDIT. Regenerate: hypr/scripts/set-wallpaper.sh
-- Override by mutating the returned table in hyprland.lua after the dofile().
return {
    accent     = "{{colors.primary.dark.hex_stripped}}",
    accent_alt = "{{colors.tertiary.dark.hex_stripped}}",
    accent_dim = "{{colors.primary_container.dark.hex_stripped}}",
    urgent     = "{{colors.error.dark.hex_stripped}}",
    surface    = "{{colors.surface_container_high.dark.hex_stripped}}",
}
