-- GENERATED BY MATUGEN -- DO NOT EDIT. Regenerate: hypr/scripts/set-wallpaper.sh
-- Override by mutating the returned table in hyprland.lua after the dofile().
-- The accent half follows the wallpaper; bg/fg/border/shadow are the fixed
-- desktop base from matugen/base.json.
return {
    accent     = "{{colors.primary.dark.hex_stripped}}",
    accent_alt = "{{colors.tertiary.dark.hex_stripped}}",
    accent_dim = "{{colors.primary_container.dark.hex_stripped}}",
    urgent     = "{{colors.error.dark.hex_stripped}}",
    surface    = "{{colors.surface_container_high.dark.hex_stripped}}",

    bg         = '{{base.bg | replace: "#", ""}}',
    fg         = '{{base.fg | replace: "#", ""}}',
    border     = '{{base.border | replace: "#", ""}}',
    shadow     = '{{base.shadow | replace: "#", ""}}',
}
