pragma Singleton

// GENERATED BY MATUGEN -- DO NOT EDIT. Regenerate: hypr/scripts/set-wallpaper.sh
// Distinct module hues are harmonized toward the wallpaper, like the prompt.
import QtQuick
import Quickshell

Singleton {
    readonly property color accent: "{{colors.primary.dark.hex}}"
    readonly property color accentAlt: "{{colors.tertiary.dark.hex}}"
    readonly property color accentDim: "{{colors.primary_container.dark.hex}}"
    readonly property color urgent: "{{colors.error.dark.hex}}"
    readonly property color red: "{{colors.rainbow_red.dark.hex}}"
    readonly property color orange: "{{colors.rainbow_orange.dark.hex}}"
    readonly property color green: "{{colors.rainbow_green.dark.hex}}"
    readonly property color cyan: "{{colors.rainbow_cyan.dark.hex}}"
    readonly property color blue: "{{colors.rainbow_blue.dark.hex}}"
    readonly property color purple: "{{colors.rainbow_purple.dark.hex}}"
    // Wallpaper-tinted dark surface -- for hovered/selected backgrounds only.
    readonly property color surface: "{{colors.surface_container_high.dark.hex}}"
}
