pragma Singleton

// GENERATED BY MATUGEN -- DO NOT EDIT. Regenerate: hypr/scripts/set-wallpaper.sh
// Role choices are kept identical to colors-waybar.css on purpose: the dashboard
// and the bar must never drift onto different accents.
import QtQuick
import Quickshell

Singleton {
    readonly property color accent: "{{colors.primary.dark.hex}}"
    readonly property color accentAlt: "{{colors.tertiary.dark.hex}}"
    readonly property color accentDim: "{{colors.primary_container.dark.hex}}"
    readonly property color urgent: "{{colors.error.dark.hex}}"
    // Wallpaper-tinted dark surface -- for hovered/selected backgrounds only.
    readonly property color surface: "{{colors.surface_container_high.dark.hex}}"
}
